#ifndef __REQUEST_H_
#define __REQUEST_H_
enum request{
	REQUEST_ECHO = 0,
	REQUEST_PHI2_INIT,
	REQUEST_CPU_READ_6502, REQUEST_CPU_READ, 
	REQUEST_CPU_WRITE_6502, REQUEST_CPU_WRITE_FLASH,
	REQUEST_PPU_READ, REQUEST_PPU_WRITE,
	REQUEST_DISK_STATUS_GET, REQUEST_DISK_READ, REQUEST_DISK_WRITE,
	REQUEST_BOTH_FLASH_STATUS,
	REQUEST_CPU_FLASH_STATUS, REQUEST_CPU_FLASH_CONFIG_SET,
	REQUEST_CPU_FLASH_PROGRAM, REQUEST_CPU_FLASH_ERASE,
	REQUEST_PPU_FLASH_STATUS, REQUEST_PPU_FLASH_CONFIG_SET,
	REQUEST_PPU_FLASH_PROGRAM, REQUEST_PPU_FLASH_ERASE
};
enum {
	READ_PACKET_SIZE = 0x0200
};
/*
request argument
bRequest       wValue  wLength
xxx_READ       address length
xxx_WRITExxxx  address length
*/
#endif
