APP_CUI = anago.exe
APP_GUI = anago_wx.exe
LIBUSB = ../libusb-win32-bin-1.2.6.0
SQUIRREL = ../SQUIRREL224
KAZZO = ../../kazzo/include
WX_CONFIG = /d/dev/wxWidgets/build_unicode_sound3/wx-config
CPPFLAGS =  -D_UNICODE
CXXFLAGS = #-finput-charset=utf-8 -fexec-charset=cp932
ICON_GUI = anago_gui.res.o
ICON_CUI = anago_cui.res.o

#unagi.res.o: unagi.rc unagi.ico
#	windres -i $< -o $@
include anago.mk
